---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/users/tokens/info":
    get:
      security:
        - bearerAuth: []
      summary: Retrieves the authenticated user's information
      tags:
        - Authentication
      responses:
        '200':
          description: Valid token - returns user info
        '401':
          description: Invalid token - unauthorized
  "/users/tokens/sign_in":
    post:
      summary: Authenticates an existing user and returns tokens
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: User authenticated successfully
        '401':
          description: Invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: test@example.com
                password:
                  type: string
                  format: password
                  example: password123
              required:
              - email
              - password
  "/users/tokens/sign_up":
    post:
      summary: Registers a new user and returns authentication tokens
      tags:
      - Authentication
      parameters: []
      responses:
        '201':
          description: User created successfully
        '422':
          description: Validation errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: test@example.com
                password:
                  type: string
                  format: password
                  example: password123
                password_confirmation:
                  type: string
                  format: password
                  example: password123
              required:
              - email
              - password
              - password_confirmation
  "/api/v1/boards":
    get:
      summary: Get a list of the boards/projects created by an user
      tags:
        - Boards
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of boards for the authenticated user
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "3"
                        type:
                          type: string
                          example: "board"
                        attributes:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 3
                            user_id:
                              type: integer
                              example: 6
                            name:
                              type: string
                              example: "Board Name"
                            created_at:
                              type: string
                              format: date-time
                              example: "2025-03-12T02:43:57.929Z"
                            updated_at:
                              type: string
                              format: date-time
                              example: "2025-03-12T02:43:57.929Z"
        '401':
          description: Invalid token - unauthorized
  "/api/v1/boards/{id}":
    get:
      summary: Retrieve a specific board by ID
      description: Returns the details of a specific board belonging to the authenticated user.
      tags:
        - Boards
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the board to retrieve
      responses:
        "200":
          description: Successfully retrieved the board
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "3"
                      type:
                        type: string
                        example: "board"
                      attributes:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 3
                          user_id:
                            type: integer
                            example: 6
                          name:
                            type: string
                            example: "Board Name"
                          created_at:
                            type: string
                            format: date-time
                            example: "2025-03-12T02:59:36.029Z"
                          updated_at:
                            type: string
                            format: date-time
                            example: "2025-03-12T02:59:36.029Z"
        "401":
          description: Invalid token - unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid token"
        "404":
          description: Board not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Board not found"
servers:
  - url: http://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
